# Site settings
title: All Your Code Base Are Belong To Us
email: an222zd@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  This web site is created for the course 1DV022, based in Kalmar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  alexnaga

# Build settings
markdown: kramdown
